authorName: shijun
experimentName: search_for_data_augmentation
trialConcurrency: 24
maxExecDuration: 10000h
maxTrialNum: 3000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_da.json
logDir: /staff/shijun/torch_projects/Lung_Seg/log/nni_log/da_log
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python nni_run.py
  codeDir: /staff/shijun/torch_projects/Lung_Seg
  gpuNum: 1
localConfig:
  gpuIndices: "0,1,4,5,6"
  useActiveGpu: True
  maxTrialNumPerGpu:  1